2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_setup.py:_flush():67] Configure stats pid to 397260
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_setup.py:_flush():67] Loading settings from /root/HORM-final/wandb/settings
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/run-20250512_053652-nv2wcjm6/logs/debug.log
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/run-20250512_053652-nv2wcjm6/logs/debug-internal.log
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_init.py:init():761] calling init triggers
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_init.py:init():784] starting backend
2025-05-12 05:36:52,849 INFO    MainThread:397260 [wandb_init.py:init():788] sending inform_init request
2025-05-12 05:36:52,852 INFO    MainThread:397260 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-12 05:36:52,852 INFO    MainThread:397260 [wandb_init.py:init():798] backend started and connected
2025-05-12 05:36:52,852 INFO    MainThread:397260 [wandb_init.py:init():891] updated telemetry
2025-05-12 05:36:52,856 INFO    MainThread:397260 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-05-12 05:36:53,976 INFO    MainThread:397260 [wandb_init.py:init():990] starting run threads in backend
2025-05-12 05:36:54,085 INFO    MainThread:397260 [wandb_run.py:_console_start():2375] atexit reg
2025-05-12 05:36:54,085 INFO    MainThread:397260 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-12 05:36:54,085 INFO    MainThread:397260 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-12 05:36:54,085 INFO    MainThread:397260 [wandb_run.py:_redirect():2315] Redirects installed.
2025-05-12 05:36:54,087 INFO    MainThread:397260 [wandb_init.py:init():1032] run started, returning control to user process
2025-05-12 05:36:54,578 INFO    MainThread:397260 [wandb_run.py:_config_callback():1261] config_cb None None {'model_config': {'name': 'Alphanet', 'num_targets': 1, 'output_dim': 1, 'readout': 'sum', 'use_pbc': False, 'direct_forces': False, 'eps': 1e-06, 'num_layers': 4, 'hidden_channels': 128, 'cutoff': 5.0, 'pos_require_grad': True, 'num_radial': 64, 'use_sigmoid': False, 'head': 16, 'a': 0.35, 'b': 0, 'main_chi1': 32, 'mp_chi1': 32, 'chi2': 8, 'hidden_channels_chi': 96, 'has_dropout_flag': True, 'has_norm_before_flag': True, 'has_norm_after_flag': False, 'reduce_mode': 'sum', 'device': 'cuda', 'compute_forces': True, 'compute_stress': False}, 'optimizer_config': {'lr': 0.0005, 'betas': [0.9, 0.999], 'weight_decay': 0, 'amsgrad': True}, 'training_config': {'datadir': '/deepprinciple-proj-dev/datasets/transition-1x/', 'bz': 8, 'num_workers': 48, 'clip_grad': True, 'gradient_clip_val': 0.1, 'ema': False, 'lr_schedule_type': 'step', 'lr_schedule_config': {'gamma': 0.85, 'step_size': 50}}}
2025-05-12 05:37:09,285 INFO    MsgRouterThr:397260 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-05-12 05:37:11,259 ERROR   MainThread:397260 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/root/miniconda3/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 178, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "/root/miniconda3/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 274, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-05-12 05:37:11,260 ERROR   MainThread:397260 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/root/miniconda3/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 178, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "/root/miniconda3/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 274, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
2025-05-12 05:37:11,260 ERROR   MainThread:397260 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/root/miniconda3/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 760, in publish_output_raw
    o.timestamp.GetCurrentTime()
  File "/root/miniconda3/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 178, in GetCurrentTime
    self.FromDatetime(datetime.datetime.utcnow())
  File "/root/miniconda3/lib/python3.10/site-packages/google/protobuf/internal/well_known_types.py", line 274, in FromDatetime
    seconds = calendar.timegm(dt.utctimetuple())
ImportError: sys.meta_path is None, Python is likely shutting down
